#!/bin/sh

# test, if arguments are correct.
if [ "$#" -ne "2" ]; then
    # one or more parameters are missing.
    exit 1
fi

# argument assignments.
ACTION=$1          # actions: update, uninstall
USER=$2

# définir le répertoire .ssh selon si l'utilisateur est root ou non
if [ "$USER" = "root" ]; then
    SSH_DIR="/root/.ssh"
else
    SSH_DIR="/home/${USER}/.ssh"
fi

AUTHORIZED_KEYS="${SSH_DIR}/authorized_keys"
NON_THEOSUSAN_PKI_FILE="${SSH_DIR}/authorized_keys.non_theosusan-pki"
THEOSUSAN_PKI_FILE="${SSH_DIR}/authorized_keys.theosusan-pki"

# Check if THEOSUSAN_PKI_FILE exists
if [ ! -f "${THEOSUSAN_PKI_FILE}" ]; then
    echo "Erreur : le fichier ${THEOSUSAN_PKI_FILE} est introuvable."
    exit 1
fi

# if NON_THEOSUSAN_PKI_FILE does not exist or is empty, we treat it as a first-time setup
if [ ! -s "${NON_THEOSUSAN_PKI_FILE}" ]; then
    # backup original authorized_keys
    cp -f "${AUTHORIZED_KEYS}" "${NON_THEOSUSAN_PKI_FILE}"
    sort "${AUTHORIZED_KEYS}" -o "${AUTHORIZED_KEYS}"
    sort "${THEOSUSAN_PKI_FILE}" -o "${THEOSUSAN_PKI_FILE}"
    comm -2 -3 "${AUTHORIZED_KEYS}" "${THEOSUSAN_PKI_FILE}" > "${NON_THEOSUSAN_PKI_FILE}"
fi

if [ "${ACTION}" = "uninstall" ]; then
    # we have to restore original authorized_keys
    cp -f "${NON_THEOSUSAN_PKI_FILE}" "${AUTHORIZED_KEYS}"
    # ... then remove all THEOSUSAN-PKI files
    rm -f "${NON_THEOSUSAN_PKI_FILE}" "${THEOSUSAN_PKI_FILE}"
    # ... and finally, delete myself.
    rm -f "$0"
    exit 0
fi

if [ "${ACTION}" = "update" ]; then
    # print a header to generated ${AUTHORIZED_KEYS}
    {
        echo "#######################################################################"
        echo "#        DO NOT EDIT THIS FILE - DO NOT EDIT THIS FILE                #"
        echo "#                                                                     #"
        echo "#  This file is generated automatically by THEOSUSAN-PKI, if you need #"
        echo "#  to modify a SSH key not maintained by THEOSUSAN-PKI, please put it #"
        echo "#  on: ${NON_THEOSUSAN_PKI_FILE}         #"
        echo "#######################################################################"
    } > "${AUTHORIZED_KEYS}"

    # merge THEOSUSAN and non-THEOSUSAN keys
    cat "${THEOSUSAN_PKI_FILE}" "${NON_THEOSUSAN_PKI_FILE}" >> "${AUTHORIZED_KEYS}"
    exit $?
fi

# EOF
