#!/bin/sh

if [ "$#" -ne "2" ]; then
    exit 1
fi

ACTION=$1
USER=$2

if [ "$USER" = "root" ]; then
    SSH_DIR="/root/.ssh"
else
    SSH_DIR="/home/${USER}/.ssh"
fi

AUTHORIZED_KEYS="${SSH_DIR}/authorized_keys"
NON_THEOSUSAN_PKI_FILE="${SSH_DIR}/authorized_keys.non_theosusan-pki"
THEOSUSAN_PKI_FILE="${SSH_DIR}/authorized_keys.theosusan-pki"

if [ "${ACTION}" = "uninstall" ]; then
    if [ -f "${NON_THEOSUSAN_PKI_FILE}" ]; then
        cp -f "${NON_THEOSUSAN_PKI_FILE}" "${AUTHORIZED_KEYS}"
    fi
    rm -f "${NON_THEOSUSAN_PKI_FILE}" "${THEOSUSAN_PKI_FILE}"
    rm -f "$0"
    exit 0
fi

if [ "${ACTION}" != "update" ]; then
    exit 1
fi

if [ ! -f "${THEOSUSAN_PKI_FILE}" ]; then
    echo "Erreur : le fichier ${THEOSUSAN_PKI_FILE} est introuvable."
    exit 1
fi

mkdir -p "${SSH_DIR}"
chmod 700 "${SSH_DIR}" 2>/dev/null || true

if [ ! -f "${AUTHORIZED_KEYS}" ]; then
    touch "${AUTHORIZED_KEYS}"
    chmod 600 "${AUTHORIZED_KEYS}"
fi

if [ ! -s "${NON_THEOSUSAN_PKI_FILE}" ]; then
    sort "${AUTHORIZED_KEYS}" -o "${AUTHORIZED_KEYS}"
    sort "${THEOSUSAN_PKI_FILE}" -o "${THEOSUSAN_PKI_FILE}"
    grep -F -x -v -f "${THEOSUSAN_PKI_FILE}" "${AUTHORIZED_KEYS}" > "${NON_THEOSUSAN_PKI_FILE}" || true
fi

{
    echo "#######################################################################"
    echo "#        DO NOT EDIT THIS FILE - DO NOT EDIT THIS FILE                #"
    echo "#                                                                     #"
    echo "#  This file is generated automatically by THEOSUSAN-PKI, if you need #"
    echo "#  to modify a SSH key not maintained by THEOSUSAN-PKI, please put it #"
    echo "#  on: ${NON_THEOSUSAN_PKI_FILE}         #"
    echo "#######################################################################"
} > "${AUTHORIZED_KEYS}"

cat "${THEOSUSAN_PKI_FILE}" "${NON_THEOSUSAN_PKI_FILE}" >> "${AUTHORIZED_KEYS}"
exit $?
